name: CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build AmazTimer
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with: 
        args: "./gradlew assembleRelease"
        
    - name: Sign apk
      uses: r0adkll/sign-android-release@v1
      with:
       releaseDirectory: app/build/outputs/apk/release
       signingKeyBase64: ${{ secrets.SIGNING_KEY }}
       alias: ${{ secrets.ALIAS }}
       keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
       keyPassword: ${{ secrets.KEY_PASSWORD }}
        
    - name: Delete edgy release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
       tag_name: edgy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create edgy release
      uses: meeDamian/github-release@v2.0.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: edgy
        name: Edgy
        body: Continuous integration build, no support will be given for this build and it might have bugs or even not work
        prerelease: true
        files: AmazTimer-EDGY.apk:$SIGNED_RELEASE_FILE
        gzip: false
